export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CONNECT_FB_SUCCESS = "CONNECT_FB_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";

//FR****10/09/2020***CATEGORIES
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDTAE_CATEGRY = "UPDTAE_CATEGRY";

//FR****08/07/2020*** BOUTIQUES
export const GET_BOUTIQUES = "GET_BOUTIQUES";
export const UPDATE_BOUTIQUE = "UPDATE_BOUTIQUE";
export const GET_BOUTQUEDETAIL = "GET_BOUTQUEDETAIL";
export const GET_BOUTQUEUSER = "GET_BOUTQUEUSER";
export const GET_ALLBOUTUSER = "GET_ALLBOUTUSER";
export const DELETE_BOUTIQUE = "DELETE_BOUTIQUE";
export const ADD_EDITOR = "ADD_EDITOR";
export const REMOVE_EDITOR = "REMOVE_EDITOR";
//FR****15/07/2020*** PRODUITS**27/07/2020***
export const GET_PRODBOUTIQUE = "GET_PRODBOUTIQUE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCTDETAIL = "GET_PRODUCTDETAIL";
export const UPDATE_PRODUIT = "UPDATE_PRODUIT";
export const GET_ALLPRODUCT = "GET_ALLPRODUCT";
export const ADD_PRODBOUT = "ADD_PRODBOUT";
export const ADD_BOUTIQUE = "ADD_BOUTIQUE";
export const UPDATE_BOUT = "UPDATE_BOUT";
export const ACTIVATE_BOUTIQUE = "ACTIVATE_BOUTIQUE";
export const DESACTIVATE_BOUTIQUE = " DESACTIVATE_BOUTIQUE";
export const ADD_BOUT = "ADD_BOUT";
// FR****** LIKES
export const GET_USERSLIKES = "GET_USERSLIKES";
export const ADD_USERLIKES = "ADD_USERLIKES";
export const DELETE_LIKE = "DELETE_LIKE";
export const GET_ALLLIKES = "GET_ALLLIKES";
// FR*** 03/08/2020***** Commandes
export const ADD_COMMANDE = "ADD_COMMANDE";
export const UPDATE_COMMANDE = "UPDATE_COMMANDE";
export const DELETE_COMMANDE = "DELETE_COMMANDE";
export const LOAD_COMMANDE = "LOAD_COMMANDE";
export const INCRE_QUANTITE = "INCRE_QUANTITE";
export const DECRE_QUANTITE = "DECRE_QUANTITE";
export const DELETE_ALLCOMMANDES = "DELETE_ALLCOMMANDES";
export const VERIF_ID = "VERIF_ID";
export const ADD_SECTIONS = "ADD_SECTIONS";
export const ADD_SECTION3 = "ADD_SECTION3";
export const ADD_SECTION4 = "ADD_SECTION4";
export const ADD_SECTION2 = "ADD_SECTION2";
export const ADD_SECTION5 = "ADD_SECTION5";
export const ADD_SECTION6 = "ADD_SECTION6";

export const POST_COMMANDE_SECTION = "POST_COMMANDE_SECTION";

export const GET_SECTIONS_BYTYPE = "GET_SECTIONS_BYTYPE";
export const ADD_SECTIONS_BYTYPE = "ADD_SECTIONS_BYTYPE";
export const DELETE_SECTIONS_BYTYPE = "DELETE_SECTIONS_BYTYPE";
export const GET_SECTIONS_GLOBAL = "GET_SECTIONS_GLOBAL";

export const GET_SECTION_TYPE2 = "GET_SECTION_TYPE2";
export const GET_SECTION_TYPE3 = "GET_SECTION_TYPE3";
export const GET_SECTION_TYPE4 = "GET_SECTION_TYPE4";
export const GET_SECTION_TYPE5 = "GET_SECTION_TYPE5";
export const GET_SECTION_TYPE6 = "GET_SECTION_TYPE6";

export const DELETE_SECTION_TYPE2 = "DELETE_SECTION_TYPE2";
export const DELETE_SECTION_TYPE3 = "DELETE_SECTION_TYPE3";
export const DELETE_SECTION_TYPE4 = "DELETE_SECTION_TYPE4";
export const DELETE_SECTION_TYPE5 = "DELETE_SECTION_TYPE5";
export const DELETE_SECTION_TYPE6 = "DELETE_SECTION_TYPE6";

export const UPDATE_SECTION_TYPE2 = "UPDATE_SECTION_TYPE2";
export const UPDATE_SECTION_TYPE3 = "UPDATE_SECTION_TYPE3";
export const UPDATE_SECTION_TYPE4 = "UPDATE_SECTION_TYPE4";
export const UPDATE_SECTION_TYPE5 = "UPDATE_SECTION_TYPE5";
export const UPDATE_SECTION_TYPE6 = "UPDATE_SECTION_TYPE6";

export const Global_ERROR = "Global_ERROR";
export const MODIF_PRIX_FINAL = "MODIF_PRIX_FINAL";
export const DELETE_SECTION_GLOBTYPE = "DELETE_SECTION_GLOBTYPE";
export const MODIF_ORDER = "MODIF_ORDER";
export const DELETE_CATEGORIE = "DELETE_CATEGORIE";

export const GET_SECTIONS = "GET_SECTIONS";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const ADD_SLIDER = "ADD_SLIDER";
export const GET_SLIDERS = "GET_SLIDERS";
export const DELETE_SLIDER = "DELETE_SLIDER";
export const UPDATE_SLIDER = "UPDATE_SLIDER";
export const POST_COMMANDE = "POST_COMMANDE";
export const GET_COMMANDE = "GET_COMMANDE";
export const DELE_COMMANDE = "DELE_COMMANDE";
export const GET_ALLCOMMANDE = "GET_ALLCOMMANDE";
export const INCRE_QUANTITE_PROD = "INCRE_QUANTITE_PROD";
export const DECRE_QUANTITE_PROD = "DECRE_QUANTITE_PROD";
export const MODIF_STATUS = "MODIF_STATUS";
export const GET_COMMANDESTATUS = "GET_COMMANDESTATUS";
export const ADD_NOTE = "ADD_NOTE";
export const ADD_TRACKING = "ADD_TRACKING";
// 24/08/2020   ***** users
export const LOAD_USERS = "LOAD_USERS";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const ACTIVATE_USER = "ACTIVATE_USER";
export const DESACTIVATE_USER = "DESACTIVATE_USER";

//**messages */

export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_MESSAGECOMM = "GET_MESSAGECOMM";
export const GET_MESSCOMDETAIL = "GET_MESSCOMDETAIL";

/****** STATUS */
export const GET_STATUS = "GET_STATUS";
export const MODIF_GROUP_STATUS = "MODIF_GROUP_STATUS";
/*******status by admin */
export const ADD_STATUS = "ADD_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const ADD_NEXT_STATUS = "ADD_NEXT_STATUS";
export const REMOVE_NEXT_STATUS = "REMOVE_NEXT_STATUS";
/*******BASE64 */
export const CONVERT_IMAGE = "CONVERT_IMAGE";

/*****SETTINGS*/
export const ADD_SECTTIINGS = "ADD_SECTTIINGS";
export const DELETE_SETTING = "DELETE_SETTING";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const GET_ALL_SETTINGS = "GET_ALL_SETTINGS";
export const GET_FILES_SETTINGS = "GET_FILES_SETTINGS";
